// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatbuffersResource
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EncounterNest8Archive : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static EncounterNest8Archive GetRootAsEncounterNest8Archive(ByteBuffer _bb) { return GetRootAsEncounterNest8Archive(_bb, new EncounterNest8Archive()); }
  public static EncounterNest8Archive GetRootAsEncounterNest8Archive(ByteBuffer _bb, EncounterNest8Archive obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EncounterNest8Archive __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatbuffersResource.EncounterNest8Table? Tables(int j) { int o = __p.__offset(4); return o != 0 ? (FlatbuffersResource.EncounterNest8Table?)(new FlatbuffersResource.EncounterNest8Table()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TablesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatbuffersResource.EncounterNest8Archive> CreateEncounterNest8Archive(FlatBufferBuilder builder,
      VectorOffset TablesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    EncounterNest8Archive.AddTables(builder, TablesOffset);
    return EncounterNest8Archive.EndEncounterNest8Archive(builder);
  }

  public static void StartEncounterNest8Archive(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTables(FlatBufferBuilder builder, VectorOffset TablesOffset) { builder.AddOffset(0, TablesOffset.Value, 0); }
  public static VectorOffset CreateTablesVector(FlatBufferBuilder builder, Offset<FlatbuffersResource.EncounterNest8Table>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTablesVectorBlock(FlatBufferBuilder builder, Offset<FlatbuffersResource.EncounterNest8Table>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartTablesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatbuffersResource.EncounterNest8Archive> EndEncounterNest8Archive(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatbuffersResource.EncounterNest8Archive>(o);
  }
  public static void FinishEncounterNest8ArchiveBuffer(FlatBufferBuilder builder, Offset<FlatbuffersResource.EncounterNest8Archive> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedEncounterNest8ArchiveBuffer(FlatBufferBuilder builder, Offset<FlatbuffersResource.EncounterNest8Archive> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
