// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatbuffersResource
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct NestHoleDistributionEncounter8Archive : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static NestHoleDistributionEncounter8Archive GetRootAsNestHoleDistributionEncounter8Archive(ByteBuffer _bb) { return GetRootAsNestHoleDistributionEncounter8Archive(_bb, new NestHoleDistributionEncounter8Archive()); }
  public static NestHoleDistributionEncounter8Archive GetRootAsNestHoleDistributionEncounter8Archive(ByteBuffer _bb, NestHoleDistributionEncounter8Archive obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NestHoleDistributionEncounter8Archive __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatbuffersResource.NestHoleDistributionEncounter8Table? Tables(int j) { int o = __p.__offset(4); return o != 0 ? (FlatbuffersResource.NestHoleDistributionEncounter8Table?)(new FlatbuffersResource.NestHoleDistributionEncounter8Table()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TablesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatbuffersResource.NestHoleDistributionEncounter8Archive> CreateNestHoleDistributionEncounter8Archive(FlatBufferBuilder builder,
      VectorOffset TablesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    NestHoleDistributionEncounter8Archive.AddTables(builder, TablesOffset);
    return NestHoleDistributionEncounter8Archive.EndNestHoleDistributionEncounter8Archive(builder);
  }

  public static void StartNestHoleDistributionEncounter8Archive(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTables(FlatBufferBuilder builder, VectorOffset TablesOffset) { builder.AddOffset(0, TablesOffset.Value, 0); }
  public static VectorOffset CreateTablesVector(FlatBufferBuilder builder, Offset<FlatbuffersResource.NestHoleDistributionEncounter8Table>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTablesVectorBlock(FlatBufferBuilder builder, Offset<FlatbuffersResource.NestHoleDistributionEncounter8Table>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartTablesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatbuffersResource.NestHoleDistributionEncounter8Archive> EndNestHoleDistributionEncounter8Archive(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatbuffersResource.NestHoleDistributionEncounter8Archive>(o);
  }
  public static void FinishNestHoleDistributionEncounter8ArchiveBuffer(FlatBufferBuilder builder, Offset<FlatbuffersResource.NestHoleDistributionEncounter8Archive> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedNestHoleDistributionEncounter8ArchiveBuffer(FlatBufferBuilder builder, Offset<FlatbuffersResource.NestHoleDistributionEncounter8Archive> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
